services:
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - mono-network

  api:
    container_name: currency-api
    build:
      dockerfile: Dockerfile
      target: development
    ports:
      - 3000:3000
    env_file:
      - .env.example
    depends_on:
      - redis
    volumes:
      - .:/app
      - /app/node_modules/
    networks:
      - mono-network

networks:
  mono-network:
    driver: bridge
